# Generated by Django 3.2.9 on 2021-11-02 17:33

import anuncios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_nota', models.IntegerField(verbose_name='Nota')),
                ('tx_comentario', models.CharField(max_length=150, null=True, verbose_name='Comentário')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_categoria', models.CharField(max_length=150, verbose_name='Nome da Categoria')),
                ('tp_categoria', models.CharField(choices=[('P', 'Produto'), ('S', 'Serviço')], max_length=1, verbose_name='Tipo de Categoria')),
                ('nm_icone', models.CharField(help_text='Opções no site https://fontawesome.com.', max_length=30, verbose_name='Nome do Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_condominio', models.CharField(max_length=150, verbose_name='Nome do Condomínio')),
                ('nm_logradouro', models.CharField(max_length=80, verbose_name='Nome do Logradouro')),
                ('nr_logradouro', models.IntegerField(null=True, verbose_name='Número')),
                ('nm_bairro', models.CharField(max_length=45, verbose_name='Bairro')),
                ('tx_complemento', models.CharField(max_length=45, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('nm_cidade', models.CharField(max_length=60, verbose_name='Cidade')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_titulo_servico', models.CharField(max_length=80, verbose_name='Titulo do Serviço')),
                ('dc_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('st_servico', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Situação do Serviço')),
                ('imagem', models.ImageField(null=True, upload_to=anuncios.models.path_and_rename, verbose_name='img')),
                ('categoria', models.ForeignKey(limit_choices_to={'tp_categoria': 'S'}, on_delete=django.db.models.deletion.CASCADE, related_name='fk_servico_categoria1', to='anuncios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_bloco', models.CharField(help_text='Nome do prédio. Ex.: Torre 1, Bloco B, Bloco Camélia.', max_length=45, verbose_name='Nome do Bloco')),
                ('nr_residencia', models.IntegerField(verbose_name='Número')),
                ('condominios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_residencia_condominio1', to='anuncios.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_produto', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('dc_produto', models.TextField(verbose_name='Descrição')),
                ('vl_produto', models.FloatField(verbose_name='Valor do Produto')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('st_produto', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Situação do Produto')),
                ('imagem', models.ImageField(null=True, upload_to=anuncios.models.path_and_rename, verbose_name='img')),
                ('categoria', models.ForeignKey(limit_choices_to={'tp_categoria': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='fk_produto_categoria1', to='anuncios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_contato', models.CharField(choices=[('Telefone', 'Telefone'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('E-Mail', 'E-Mail')], max_length=45, verbose_name='Tipo de Contato')),
                ('tx_contato', models.CharField(max_length=80, verbose_name='Contato')),
                ('condominios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_contato_condominio1', to='anuncios.condominio')),
            ],
        ),
    ]
