# Generated by Django 3.2.9 on 2021-11-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0004_auto_20211102_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='tx_complemento',
            field=models.CharField(max_length=45, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(default=users.models.User, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_produto_user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
