# Generated by Django 3.2.8 on 2021-11-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_alter_produto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tp_contato',
            field=models.CharField(choices=[('Telefone', 'Telefone'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('E-Mail', 'E-Mail'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=45, verbose_name='Tipo de Contato'),
        ),
    ]
